# Generated by Django 5.2.6 on 2025-10-01 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageContacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cinema_name", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("coordinates", models.CharField(max_length=100)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="page/logo"),
                ),
                ("status", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "seo_block",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.seoblock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PageElse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="page/logo"),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("status", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=False)),
                (
                    "gallery",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.gallery",
                    ),
                ),
                (
                    "seo_block",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.seoblock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PageMain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number1", models.SmallIntegerField()),
                ("phone_number2", models.SmallIntegerField()),
                ("status", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("seo_text", models.TextField()),
                (
                    "seo_block",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.seoblock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PageNewsPromos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="page/logo"),
                ),
                ("status", models.BooleanField(default=False)),
                ("url", models.URLField()),
                (
                    "gallery",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.gallery",
                    ),
                ),
                (
                    "seo_block",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.seoblock",
                    ),
                ),
            ],
        ),
    ]
