# Generated by Django 5.2.6 on 2025-10-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemain',
            name='phone_number1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pagemain',
            name='phone_number2',
            field=models.CharField(max_length=20),
        ),
    ]
