# Generated by Django 5.2.6 on 2025-10-08 07:56

from django.db import migrations


def create_default_pages(apps, schema_editor):
    PageMain = apps.get_model('page', 'PageMain')
    PageContacts = apps.get_model('page', 'PageContacts')
    PageElse = apps.get_model('page', 'PageElse')
    
    # Создать главную страницу, если её нет
    if not PageMain.objects.exists():
        PageMain.objects.create(
            phone_number1='0994718721',
            phone_number2='0994718722',
            status=True,
            seo_text="Добро пожаловать в наш кинотеатр! Лучшие фильмы и удобные залы ждут вас."
        )
    
    # Создать страницу контактов, если её нет
    if not PageContacts.objects.exists():
        PageContacts.objects.create(
            cinema_name="КиноЦентр",
            address="ул. Примерная, 123, г. Город",
            coordinates="50.4501, 30.5234",
            status=True
        )
    
    # Создать стандартные страницы PageElse
    default_pages = [
        {"name": "О кинотеатре", "description": "Информация о нашем кинотеатре, его истории и особенностях."},
        {"name": "Кафе-бар", "description": "Наше кафе предлагает разнообразное меню и напитки."},
        {"name": "VIP зал", "description": "Премиальный зал с повышенным комфортом и сервисом."},
        {"name": "Реклама", "description": "Рекламные предложения и партнерские программы."},
        {"name": "Детская комната", "description": "Специальная зона для детей с развлечениями и играми."},
    ]
    
    for page_data in default_pages:
        if not PageElse.objects.filter(name=page_data["name"]).exists():
            PageElse.objects.create(
                name=page_data["name"],
                description=page_data["description"],
                status=True,
                can_delete=False  # Системные страницы нельзя удалять
            )


def reverse_create_default_pages(apps, schema_editor):
    # Обратная операция - удалить созданные записи
    PageMain = apps.get_model('page', 'PageMain')
    PageContacts = apps.get_model('page', 'PageContacts')
    PageElse = apps.get_model('page', 'PageElse')
    
    PageMain.objects.all().delete()
    PageContacts.objects.all().delete()
    PageElse.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_pagemain_phone_number1_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_pages, reverse_create_default_pages),
    ]
