# Generated by Django 5.2.6 on 2025-10-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0003_alter_pageelse_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageelse",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
