# Generated by Django 5.2.6 on 2025-10-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20251008_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontacts',
            name='address_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pagecontacts',
            name='address_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pagecontacts',
            name='cinema_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pagecontacts',
            name='cinema_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pageelse',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='pageelse',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='pageelse',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pageelse',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pagemain',
            name='seo_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pagemain',
            name='seo_text_ru',
            field=models.TextField(null=True),
        ),
    ]
