# Generated by Django 5.2.6 on 2025-10-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_pagecontacts_address_en_pagecontacts_address_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageelse',
            old_name='description_en',
            new_name='description_uk',
        ),
        migrations.RenameField(
            model_name='pageelse',
            old_name='name_en',
            new_name='name_uk',
        ),
        migrations.RenameField(
            model_name='pagemain',
            old_name='seo_text_en',
            new_name='seo_text_uk',
        ),
        migrations.RemoveField(
            model_name='pagecontacts',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='pagecontacts',
            name='address_ru',
        ),
        migrations.RemoveField(
            model_name='pagecontacts',
            name='cinema_name_en',
        ),
        migrations.RemoveField(
            model_name='pagecontacts',
            name='cinema_name_ru',
        ),
    ]
