# Generated by Django 5.2.6 on 2025-11-18 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_galleryimage_image"),
        ("page", "0004_alter_pageelse_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagenewssales",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="pagenewssales",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="pagenewssales",
            name="description_uk",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="pagenewssales",
            name="logo",
            field=models.ImageField(upload_to="page/logo", verbose_name="Главная картинка"),
        ),
        migrations.AlterField(
            model_name="pagenewssales",
            name="publish_date",
            field=models.DateField(verbose_name="Дата публикации"),
        ),
        migrations.AlterField(
            model_name="pagenewssales",
            name="seo_block",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.seoblock"
            ),
        ),
        migrations.AlterField(
            model_name="pagenewssales",
            name="video_url",
            field=models.URLField(verbose_name="Ссылка на видео"),
        ),
    ]
