# Generated by Django 5.2.6 on 2025-10-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_rename_description_en_pageelse_description_uk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemain',
            name='seo_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagemain',
            name='seo_text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagemain',
            name='seo_text_uk',
            field=models.TextField(blank=True, null=True),
        ),
    ]
