# Generated by Django 5.2.6 on 2025-11-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0005_alter_pagenewssales_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageelse",
            name="logo",
            field=models.ImageField(upload_to="page/logo"),
        ),
    ]
