# Generated by Django 5.2.6 on 2025-10-15 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_gallery_name_en_remove_gallery_name_ru_and_more'),
        ('page', '0006_alter_pagemain_seo_text_alter_pagemain_seo_text_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageNewsSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('news', 'Новость'), ('sale', 'Акция')], max_length=10, verbose_name='Тип')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('name_uk', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_uk', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('status', models.BooleanField(default=False, verbose_name='Активна')),
                ('gallery', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gallery')),
                ('seo_block', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.seoblock')),
            ],
            options={
                'verbose_name': 'Новость/Акция',
                'verbose_name_plural': 'Новости и Акции',
                'ordering': ['-publish_date', '-date'],
            },
        ),
        migrations.DeleteModel(
            name='PageNewsPromos',
        ),
    ]
