# Generated by Django 5.2.6 on 2025-10-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_pagenewssales_delete_pagenewspromos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagenewssales',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='page/logo', verbose_name='Главная картинка'),
        ),
    ]
