# Generated by Django 5.2.6 on 2025-10-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seoblock',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='seoblock',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='seoblock',
            name='keywords_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Word'),
        ),
        migrations.AddField(
            model_name='seoblock',
            name='keywords_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Word'),
        ),
        migrations.AddField(
            model_name='seoblock',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='seoblock',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
    ]
