# Generated by Django 5.2.6 on 2025-10-28 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='GalleryImage',
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='seoblock',
            options={},
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
