# Generated by Django 5.2.6 on 2025-11-09 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_image_galleryimage_alter_gallery_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="mailing_files/", verbose_name="Файл")),
                ("original_name", models.CharField(max_length=255, verbose_name="Название файла")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата загрузки")),
                ("file_size", models.IntegerField(default=0, verbose_name="Размер файла (байты)")),
            ],
            options={
                "verbose_name": "Файл рассылки",
                "verbose_name_plural": "Файлы рассылки",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("send_to_all", models.BooleanField(default=False, verbose_name="Отправить всем")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В очереди"),
                            ("processing", "Выполняется"),
                            ("completed", "Завершена"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("total_recipients", models.IntegerField(default=0, verbose_name="Всего получателей")),
                ("sent_count", models.IntegerField(default=0, verbose_name="Отправлено")),
                ("failed_count", models.IntegerField(default=0, verbose_name="Ошибок")),
                (
                    "celery_task_id",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="ID задачи Celery"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создана")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="Начата")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="Завершена")),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.mailingfile",
                        verbose_name="Прикрепленный файл",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MailingRecipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Ожидает отправки"), ("sent", "Отправлено"), ("failed", "Ошибка")],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True, verbose_name="Сообщение об ошибке")),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="Отправлено")),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="core.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
                "unique_together": {("mailing", "user")},
            },
        ),
    ]
