# Generated by Django 5.2.6 on 2025-10-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gallery_name_en_gallery_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='seoblock',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='seoblock',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='seoblock',
            name='keywords_en',
        ),
        migrations.RemoveField(
            model_name='seoblock',
            name='keywords_ru',
        ),
        migrations.RemoveField(
            model_name='seoblock',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='seoblock',
            name='title_ru',
        ),
    ]
