# Generated by Django 5.2.6 on 2025-11-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_mailingfile_mailing_mailingrecipient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seoblock",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="seoblock",
            name="keywords",
            field=models.CharField(max_length=50, verbose_name="Word"),
        ),
        migrations.AlterField(
            model_name="seoblock",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="seoblock",
            name="url",
            field=models.URLField(verbose_name="URL"),
        ),
    ]
