# Generated by Django 5.2.6 on 2025-11-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_seoblock_description_alter_seoblock_keywords_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seoblock",
            name="keywords",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
