# Generated by Django 5.2.6 on 2025-11-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_seoblock_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seoblock",
            name="keywords",
            field=models.CharField(max_length=255, verbose_name="Keywords"),
        ),
    ]
