# Generated by Django 5.2.6 on 2025-11-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_seoblock_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryimage",
            name="image",
            field=models.ImageField(upload_to="gallery_images/"),
        ),
    ]
