# Generated by Django 5.2.6 on 2025-11-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
