# Generated by Django 5.2.6 on 2025-11-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_customuser_nickname"),  # Django сам подставит правильное имя
    ]

    operations = [
        # Сначала удаляем старый unique constraint, если он есть
        migrations.AlterField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        # Добавляем новый conditional unique constraint
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.UniqueConstraint(
                fields=["nickname"], condition=models.Q(nickname__isnull=False), name="unique_nickname_when_not_null"
            ),
        ),
    ]
