# Generated by Django 5.2.6 on 2025-11-18 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_customuser_nickname"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
    ]
