# Generated by Django 5.2.6 on 2025-10-31 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banner", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannerItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="banner_image"),
                ),
                ("url", models.URLField(blank=True)),
                ("text", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="BannerSlider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="На главной верх", max_length=255)),
                (
                    "rotation_time",
                    models.PositiveIntegerField(choices=[(5, "5"), (10, "10"), (15, "15")], default=5),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="BottomBannerItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="banner_image"),
                ),
                ("url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="BottomBannerSlider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="На главной Новости Акции внизу", max_length=255),
                ),
                (
                    "rotation_time",
                    models.PositiveIntegerField(choices=[(5, "5"), (10, "10"), (15, "15")], default=5),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name="BannerSettings",
        ),
        migrations.RemoveField(
            model_name="bannerbackground",
            name="just_color",
        ),
        migrations.RemoveField(
            model_name="bannerbackground",
            name="name",
        ),
        migrations.AddField(
            model_name="bannerbackground",
            name="title",
            field=models.CharField(default="Сквозной банер на заднем фоне", max_length=255),
        ),
        migrations.AddField(
            model_name="bannerbackground",
            name="use_image",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="banneritem",
            name="slider",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="banner.bannerslider"),
        ),
        migrations.AddField(
            model_name="bottombanneritem",
            name="slider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="banner.bottombannerslider",
            ),
        ),
    ]
