# Generated by Django 5.2.6 on 2025-11-11 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banner", "0002_banneritem_bannerslider_bottombanneritem_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banneritem",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "Элемент верхнего баннера",
                "verbose_name_plural": "Элементы верхнего баннера",
            },
        ),
        migrations.AlterModelOptions(
            name="bannerslider",
            options={"verbose_name": "Верхний баннер", "verbose_name_plural": "Верхние баннеры"},
        ),
        migrations.AlterModelOptions(
            name="bottombanneritem",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "Элемент нижнего баннера",
                "verbose_name_plural": "Элементы нижнего баннера",
            },
        ),
        migrations.AlterModelOptions(
            name="bottombannerslider",
            options={"verbose_name": "Нижний баннер", "verbose_name_plural": "Нижние баннеры"},
        ),
        migrations.AddField(
            model_name="banneritem",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bottombanneritem",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="banneritem",
            name="slider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="items", to="banner.bannerslider"
            ),
        ),
        migrations.AlterField(
            model_name="bottombanneritem",
            name="slider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="items", to="banner.bottombannerslider"
            ),
        ),
    ]
