# Generated by Django 5.2.6 on 2025-10-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinema',
            old_name='conditions_en',
            new_name='conditions_uk',
        ),
        migrations.RenameField(
            model_name='cinema',
            old_name='description_en',
            new_name='description_uk',
        ),
        migrations.RenameField(
            model_name='cinema',
            old_name='name_en',
            new_name='name_uk',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='description_en',
            new_name='description_uk',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='title_en',
            new_name='title_uk',
        ),
    ]
