# Generated by Django 5.2.6 on 2025-10-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_session_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
