# Generated by Django 5.2.6 on 2025-10-12 14:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_rename_conditions_en_cinema_conditions_uk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='type2d',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='type3d',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='typeimax',
        ),
        migrations.AddField(
            model_name='movie',
            name='formats',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('IMAX', 'IMAX')], max_length=10), blank=True, default=list, size=None, verbose_name='Форматы показа'),
        ),
    ]
