# Generated by Django 5.2.6 on 2025-10-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_remove_movie_type2d_remove_movie_type3d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания проката'),
        ),
        migrations.AddField(
            model_name='movie',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала проката'),
        ),
    ]
