# Generated by Django 5.2.6 on 2025-10-31 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0004_alter_cinema_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="hall",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="hall",
            name="cinema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="halls",
                to="cinema.cinema",
            ),
        ),
    ]
