# Generated by Django 5.2.6 on 2025-10-20 18:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_movie_end_date_movie_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='SeoBlock1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('keywords', models.CharField(blank=True, max_length=50, null=True, verbose_name='Word')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='seo_block',
        ),
        migrations.AddField(
            model_name='cinema',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cinema',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='cinema/banners/'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='cinema/logos/'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='gallery1',
            field=models.ManyToManyField(blank=True, to='cinema.image1'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='seo_block1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema.seoblock1'),
        ),
    ]
