# Generated by Django 5.2.6 on 2025-10-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0005_hall_created_at_alter_hall_cinema"),
    ]

    operations = [
        migrations.AddField(
            model_name="hall",
            name="scheme_data",
            field=models.JSONField(blank=True, null=True, verbose_name="Схема зала"),
        ),
    ]
