# Generated by Django 5.2.6 on 2025-10-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0006_hall_scheme_data"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="hall",
            unique_together={("cinema", "name")},
        ),
        migrations.AddField(
            model_name="hall",
            name="description_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hall",
            name="description_uk",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hall",
            name="name_ru",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="hall",
            name="name_uk",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="hall",
            unique_together={
                ("cinema", "name"),
                ("cinema", "name_ru"),
                ("cinema", "name_uk"),
            },
        ),
    ]
