# Generated by Django 5.2.6 on 2025-10-31 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0007_alter_hall_unique_together_hall_description_ru_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hall",
            name="rows",
        ),
        migrations.RemoveField(
            model_name="hall",
            name="seats_per_row",
        ),
    ]
