# Generated by Django 5.2.6 on 2025-11-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0008_remove_hall_rows_remove_hall_seats_per_row"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hall",
            name="name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="hall",
            name="name_ru",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="hall",
            name="name_uk",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
