# Generated by Django 5.2.6 on 2025-11-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0009_alter_hall_name_alter_hall_name_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="format",
            field=models.CharField(
                choices=[("2D", "2D"), ("3D", "3D"), ("IMAX", "IMAX")],
                default="2D",
                max_length=10,
                verbose_name="Формат",
            ),
        ),
    ]
