# Generated by Django 5.2.6 on 2025-11-17 12:05

import datetime

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0010_session_format"),
        ("core", "0005_alter_seoblock_description_alter_seoblock_keywords_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(verbose_name="Описание фильма"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Описание фильма"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="description_uk",
            field=models.TextField(null=True, verbose_name="Описание фильма"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="end_date",
            field=models.DateField(default=datetime.date(2000, 1, 1), verbose_name="Дата окончания проката"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movie",
            name="formats",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(choices=[("2D", "2D"), ("3D", "3D"), ("IMAX", "IMAX")], max_length=10),
                default=list,
                size=None,
                verbose_name="Форматы показа",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="gallery",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.gallery"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.ImageField(default=datetime.date(2000, 1, 1), upload_to="posters/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movie",
            name="seo_block",
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.seoblock"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="start_date",
            field=models.DateField(verbose_name="Дата начала проката"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="trailer_url",
            field=models.URLField(verbose_name="Ссылка на трейлер"),
        ),
    ]
