# Generated by Django 5.2.6 on 2025-11-18 08:39

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0011_alter_movie_description_alter_movie_description_ru_and_more"),
        ("core", "0007_alter_seoblock_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание фильма"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание фильма"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="description_uk",
            field=models.TextField(blank=True, null=True, verbose_name="Описание фильма"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата окончания проката"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="formats",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(choices=[("2D", "2D"), ("3D", "3D"), ("IMAX", "IMAX")], max_length=10),
                blank=True,
                default=list,
                size=None,
                verbose_name="Форматы показа",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="gallery",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.gallery"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.ImageField(blank=True, null=True, upload_to="posters/"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="seo_block",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.seoblock"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата начала проката"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="trailer_url",
            field=models.URLField(blank=True, null=True, verbose_name="Ссылка на трейлер"),
        ),
    ]
