# Generated by Django 5.2.6 on 2025-11-18 16:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0012_alter_movie_description_alter_movie_description_ru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cinema",
            name="banner",
            field=models.ImageField(upload_to="cinema/banners/"),
        ),
        migrations.AlterField(
            model_name="cinema",
            name="conditions",
            field=models.TextField(verbose_name="Условия"),
        ),
        migrations.AlterField(
            model_name="cinema",
            name="conditions_ru",
            field=models.TextField(null=True, verbose_name="Условия"),
        ),
        migrations.AlterField(
            model_name="cinema",
            name="conditions_uk",
            field=models.TextField(null=True, verbose_name="Условия"),
        ),
        migrations.AlterField(
            model_name="cinema",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="cinema",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="cinema",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="cinema",
            name="description_uk",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="cinema",
            name="logo",
            field=models.ImageField(upload_to="cinema/logos/"),
        ),
        migrations.AlterField(
            model_name="hall",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="hall/banners/"),
        ),
        migrations.AlterField(
            model_name="hall",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="hall",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="hall",
            name="description_uk",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="hall",
            name="scheme_data",
            field=models.JSONField(verbose_name="Схема зала"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(verbose_name="Описание фильма"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Описание фильма"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="description_uk",
            field=models.TextField(null=True, verbose_name="Описание фильма"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="end_date",
            field=models.DateField(verbose_name="Дата окончания проката"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="formats",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(choices=[("2D", "2D"), ("3D", "3D"), ("IMAX", "IMAX")], max_length=10),
                default=list,
                size=None,
                verbose_name="Форматы показа",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.ImageField(upload_to="posters/"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="start_date",
            field=models.DateField(verbose_name="Дата начала проката"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="trailer_url",
            field=models.URLField(verbose_name="Ссылка на трейлер"),
        ),
    ]
