# Generated by Django 5.2.6 on 2025-11-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0013_alter_cinema_banner_alter_cinema_conditions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hall",
            name="banner",
            field=models.ImageField(upload_to="hall/banners/"),
        ),
    ]
